set nocompatible
"=======================================================================
" for local setting
set tags+=../tags,../../tags,../../../tags,../../../../tags,../../../../../tags
colorscheme beauty256

" vimshell
let g:VimShell_EnableInteractive = 1

"=======================================================================
" Common options
syntax on
"set incsearch
set noincsearch
set nobk
set number
"set smartcase
set wildmode=list:full
set autoindent
set backspace=indent,eol,start
set encoding=japan
set grepprg=findstr\ $*
set hlsearch
set iminsert=0
set imsearch=0
set listchars=eol:$,tab:>-
"set nowrap
set ruler
set shiftwidth=2
set tabstop=2
set expandtab
set shortmess+=I
set showcmd
set visualbell
set lines=50
set columns=85
set swb="split"

"=======================================================================
" Folding stuff
hi Folded guifg=#b08020 guibg=#f0e8c0 cterm=bold ctermbg=DarkGrey ctermfg=lightblue
hi FoldColumn guibg=grey78 gui=Bold guifg=DarkBlue
set foldcolumn=2
set foldclose=
set foldmethod=indent
set foldnestmax=10
set foldlevel=0
set fillchars=vert:\|,fold:\
set foldminlines=3
" Toggle fold state between closed and opened.
"
" If there is no fold at current line, just moves forward.
" If it is present, reverse it's state.
fu! ToggleFold()
  if foldlevel('.') == 0
    normal! l
  else
    if foldclosed('.') < 0
       . foldclose
    else
       . foldopen
    endif
  endif
  echo
endf

" Map this function to Space key.
noremap <space> :call ToggleFold()<CR>

