set nocompatible
source $VIMRUNTIME/vimrc_example.vim
source $VIMRUNTIME/mswin.vim
source $VIMRUNTIME/encode.vim
behave mswin

"=======================================================================
set diffexpr=MyDiff()
function MyDiff()
  let opt = ''
  if &diffopt =~ 'icase' | let opt = opt . '-i ' | endif
  if &diffopt =~ 'iwhite' | let opt = opt . '-b ' | endif
  silent execute '!C:\Vim\vim62\diff -a ' . opt . '"' . v:fname_in . '" "' . v:fname_new . '" > "' . v:fname_out . '"'
endfunction

"=======================================================================
"  vimrc for janus

" Source other vim command
if !has("gui_win32")
  if filereadable( $HOME . "/.exrc" )
    source ~/.exrc
  endif
  if filereadable( $HOME . "/.vim/janus.vim" )
"    source ~/.vim/janus.vim
  endif
else
  if $TERM != ""
    set shell=c:/cygwin/bin/bash.exe
  endif
"   source ~/.vim/janus.vim
"   source ~/.vim/plugin/taglist.vim
"   source ~/.vim/plugin/cppcomplete.vim
endif

"=======================================================================
" Common options
syntax on
"set incsearch
set noincsearch
set nobk
set number
"set smartcase
set wildmode=list:full
set autoindent
set backspace=indent,eol,start
set encoding=japan
set grepprg=findstr\ $*
set hlsearch
set iminsert=0
set imsearch=0
set listchars=eol:$,tab:>-
"set nowrap
set ruler
set shiftwidth=2
set tabstop=2
set expandtab
set shortmess+=I
set showcmd
set visualbell
set lines=50
set columns=85
set swb="split"
colorscheme beauty256

"=======================================================================
" Folding stuff
hi Folded guifg=#b08020 guibg=#f0e8c0 cterm=bold ctermbg=DarkGrey ctermfg=lightblue
hi FoldColumn guibg=grey78 gui=Bold guifg=DarkBlue
set foldcolumn=2
set foldclose=
set foldmethod=indent
set foldnestmax=10
set foldlevel=0
set fillchars=vert:\|,fold:\
set foldminlines=3
" Toggle fold state between closed and opened.
"
" If there is no fold at current line, just moves forward.
" If it is present, reverse it's state.
fu! ToggleFold()
  if foldlevel('.') == 0
    normal! l
  else
    if foldclosed('.') < 0
       . foldclose
    else
       . foldopen
    endif
  endif
  echo
endf

" Map this function to Space key.
noremap <space> :call ToggleFold()<CR>

"=======================================================================
if has("gui_win32")
"    source ~/.vim/colors/jancol.vim
"	set guifont=ÇlÇr_ÉSÉVÉbÉN:h10:cSHIFTJIS
	set guifont=konatuTohaba:h10:cSHIFTJIS
"    autocmd GUIEnter * simalt ~x
else
  au BufNewFile,BufRead fstab setf fstab
  if has("gui_running")
    colorscheme jancol
    set imactivatekey=S-space
    inoremap <silent> <ESC> <ESC>:set iminsert=0<CR>
    if $HOSTNAME == "vaio"
      set guifontset=-alias-fixed-medium-r-normal-*-*-140-*-*-c-*-jisx0201.1976-0
    else
      set guifontset=-alias-fixed-medium-r-normal-*-*-160-*-*-c-*-jisx0201.1976-0
    endif
  else
    colorscheme peachpuff
    set mouse=a
  endif
endif

"=======================================================================
" for autocmd
if has("autocmd")
  filetype plugin indent on
  autocmd FileType text setlocal textwidth=78
  autocmd BufReadPost *
          \ if line("'\"") > 0 && line("'\"") <= line("$") |
          \   exe "normal g`\"" |
          \ endif
  autocmd BufEnter * :cd %:p:h
endif

"=======================================================================
" for local setting
set tags+=../tags,../../tags,../../../tags,../../../../tags,../../../../../tags

